language: python
python:
  - "3.5"
notifications:
  email: false

# command to install dependencies

before_install:
  - sudo apt-get update
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: make tox
