---
title: "declaratorias"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github('diegovalle/mxmaps')
library(mxmaps)
library(tidyverse)
library(dbrsocial)
library(stats)
library(magrittr)
```

# Load Data
```{r pressure, echo=FALSE}
dotenv::load_dot_env("../../politica_preventiva/.env")
con <- prev_connect()
coneval_data <-dbrsocial::load_table(con,raw,coneval_municipios) %>% dbrsocial::retrieve_result(-1) %>% 
  filter(data_date == '2015-a') 
# coneval <- read_csv("coneval.csv")

```

# Compute Hierarchical Clustering
```{r}
data("df_mxmunicipio")
coneval_complete <- coneval_data %>% select(cve_muni,
                                            starts_with("ic_"),
                                            plb_m_porcentaje,
                                            plb_porcentaje) %>% drop_na()
res.hc <- coneval_complete %>% 
  select(ends_with('porcentaje')) %>%
  dist(method = "euclidean") %>% # Compute dissimilarity matrix
  hclust(method = "ward.D2") %>% # Compute hierachical clustering
  cutree(k = 5)
coneval_complete$cluster.h <- res.hc

```


# Plot Map
```{r}
coneval_complete %>% group_by(cluster.h) %>%
  summarise(n=n())

coneval_complete %>% group_by(cluster.h) %>% 
  summarise_all(mean) %>%
  arrange(ic_rezedu_porcentaje) %>% select(cluster.h, ends_with("porcentaje")) %>% write_csv("temp.csv")

df_mxmunicipio <- left_join(df_mxmunicipio, coneval_complete, by=c("region"="cve_muni"))

df_mxmunicipio$value <-  as.character(df_mxmunicipio$cluster.h)

df_mxmunicipio$value <- ordered(df_mxmunicipio$value, levels = c("1","2","3","4","5"),
                                labels =  c("Muy Bajo", "Bajo", "Medio", "Alto", "Muy Alto"))


 
```


```{r}
 cols <- c("Muy Bajo"= "#84b274", 
           "Bajo"= "#CCCC99", 
           "Medio"= "#ffffbf", 
           "Alto"= "#fdae61", 
           "Muy Alto"= "#d7191c")

map<-mxmunicipio_choropleth(df_mxmunicipio %>% drop_na(value)) +
  scale_fill_manual(values=cols, name="Cluster de \n Carencias")

map
```

