# YAML file indicating feature task dependencies.
# Dependencies are to be listed according to the schema
# their PostgreSQL table is located in:
# clean_dependencies: "clean"
# features_dependencies: "features"
# models_dependencies: "models"
cuis_carencias:
    clean_dependencies:
        - cuis_historico_integrante
        - cuis_historico_se_integrante
        - cuis_historico_se_vivienda
        - cuis_historico_vivienda
cuis_ingreso:
    clean_dependencies:
        - cuis_historico_integrante
        - cuis_historico_se_integrante
        - cuis_historico_se_vivienda
        - cuis_historico_vivienda
enigh_carencias:
    clean_dependencies:
        - enigh_hogares
        - enigh_ingresos
        - enigh_poblacion
        - enigh_trabajos
        - enigh_viviendas
enigh_ingreso:
    clean_dependencies:
        - enigh_hogares
        - enigh_ingresos
        - enigh_poblacion
        - enigh_trabajos
        - enigh_viviendas
crimenes_tasas:
    clean_dependencies:
        - delitos_comun
recursos_hospitales:
    clean_dependencies:
        - recursos_hospitales
intercensal_viviendas_2015:
    clean_dependencies:
        - intercensal_viviendas_2015
intercensal_personas_2015:
    clean_dependencies:
        - intercensal_personas_2015
enigh_vulnerabilidades:
    clean_dependencies:
        - enigh_trabajos
        - enigh_ingresos
        - enigh_poblacion
        - enigh_concentrados
imco_info_publica:
    clean_dependencies:
        - imco_info_publica
    raw_dependencies:
        - geom_estados
inegi_jueces:
    clean_dependencies:
        - inegi_jueces
    raw_dependencies:
        - geom_estados
inegi_agentes_fiscales:
    clean_dependencies:
        - inegi_agentes_fiscales
    raw_dependencies:
        - geom_estados
inform_mun:
    clean_dependencies:
        - cenapred_app_municipios
        - cngmd_proteccion_civil
        - cngmd_predial
        - cngmd_drenaje
        - cngmd_recoleccion_basura
        - cfe
        - coneval_municipios
    features_dependencies:
        - crimenes_tasas
        - intercensal_personas_2015
        - intercensal_viviendas_2015
