coneval:
- coneval_estados
- coneval_municipios
cuenta_publica:
- cuenta_publica_anual
- cuenta_publica_trimestral
pub_agrupaciones:
- pub_agrupaciones
catalogo_ubicaciones:
- geoms_municipios
- geoms_estados
reporte_programas:
- cuaps_programas
- cuaps_apoyos
- cuaps_criterios
- inventario_coneval_estatales
- inventario_coneval_federales
- listado_coneval_federales
