# YAML file indicating semantic task dependencies.
# Dependencies are to be listed according to the schema
# their PostgreSQL table is located in:
# tidy_dependencies: "tidy"

perfil:
    tidy_dependencies:
        - perfil_ubicaciones
        - temporal_ubicaciones
        # TODO() Add dbrsocial to rtask
        # - pub_agg
