#!/usr/bin/env Rscript
library(rlang)
library(tidyverse)


query <- 'select  data_date as fecha,
        proyecto,
		factor,
		folioviv,
		foliohog,
		numren,
		tam_loc,
		rururb,
		cve_ent,
		edad,
		sexo,
		round(tamhogesc::numeric,2) as tamhogesc,
		ic_rezedu,
		anac_e,
		inas_esc,
		niv_ed,
		ic_asalud,
		ic_segsoc,
		ss_dir,
		pea,
		par,
		jef_ss,
		cony_ss,
		hijo_ss,
		s_salud,
		pam,
		ic_cv,
		icv_hac,
		ic_sbv,
		isb_combus,
		ic_ali,
		id_men,
		tot_iaad,
		tot_iamen,
		ins_ali,
		plb_m,
		plb,
		round(ictpc::numeric,2) as ictpc,
		i_privacion,
		pobreza,
		pobreza_e,
		pobreza_m,
		vul_car,
		vul_ing,
		no_pobv,
		carencias,
		carencias3,
		cuadrantes,
		round(prof_b1::numeric, 2) as prof_b1,
		round(prof_bm1::numeric, 2) as prof_bm1,
		round(profun::numeric, 2) as profun,
		round(int_pob::numeric, 2) as int_pob,
		round(int_pobe::numeric, 2) as int_pobe,
		round(int_vulcar::numeric, 2) as int_vulcar,
		round(int_caren::numeric, 2) as int_caren,
		round(ict::numeric, 2) as ict,
		actualizacion_sedesol,
		data_date  from raw.coneval_estados'

make_clean <- function(pipeline_task, con){
  df <- tbl(con, sql(query))
}
