---
title: "analisis exploratorio BD"
author: "rsanchezavalos"
date: "October 21, 2016"
output: html_document
---

# Monitor de Sequía y disponibilidad de Agua

## Protocolo Nacional de Alerta Ante Sequía http://www.pronacose.gob.mx/pronacose14/Contenido/Documentos/Protocolo_AlertarSequias.pdf

## Monitor de Sequía [bimestral]
Se basa en la obtención e interpretación de diversos índices o indicadores de sequía, que mediante un consenso se determinan las regiones afectadas por este fenómeno, de acuerdo a la escala de intensidades que va desde Anormalmente seco (D0), Sequía moderada (D1), Sequía severa (D2), Sequía Extrema (D3) hasta Sequía excepcional (D4).
Este monitor forma parte del Monitor de Sequía de América del Norte (NADM) y consta de una serie de materiales que incluyen una descripción de la sequía en el país, el conteo de municipios afectados por las diferentes categorías de sequía, tablas y gráficos de porcentaje de área afectada por sequía a nivel nacional, estatal, 13 Regiones Hidrológico-Administrativas y 26 Consejos de cuenca.

http://smn.cna.gob.mx/es/climatologia/monitor-de-sequia/monitor-de-sequia-en-mexico


## SEQUÍA HIDROLÓGICA (SDI) [bimestral] MUNICIPAL IMAGEN


http://www.pronacose.gob.mx/Contenido.aspx?n1=4&n2=21



# ÍNDICE DE VULNERABILIDAD GLOBAL [CONAGUA] MUNICIPAL / pdf

Factores (zj) de la Vulnerabilidad, según el IPCC usados en el estudio de la CONAGUA (2011), a partir de los resultados de la AA2030:
Grado de exposición
- 1a: Relación brecha hídrica 2030/Oferta sustentable
- 1b: Frecuencia de sequías: A, agrícola; H, hidrológica; S, periodo corto (menos de 6 meses); L, periodo largo (más de 6 meses)
Sensibilidad
- 2a: Población al 2030
- 2b: PIB
- 2c: Impacto económico en la agricultura
Capacidad de adaptación
- 3a: Sobre explotación de los acuífero

http://www.pronacose.gob.mx/pronacose14/contenido/documentos/TablaVulTodoslosMpios_2457_01042016.pdf


# CENAPRED
Indicadores Municipales de Peligro, Exposición y Vulnerabilidad
http://www.atlasnacionalderiesgos.gob.mx/archivo/indicadores-municipales.html
