	---
title: "analisis exploratorio BD"
author: "rsanchezavalos"
date: "October 21, 2016"
output: html_document
---

## CONAGUA

### Monitor de Sequía en México
	El Servicio Meteorológico Nacional (SMN) es la dependencia oficial del gobierno mexicano encargada de proporcionar información meteorológica (estado del tiempo) y climatológica. Para ello utiliza las redes de observación tales como estaciones automáticas, observatorios sinópticos, radares, estaciones de radiosondeo y estaciones receptoras de imágenes de satélite. Uno de los fenómenos climáticos que más afecta a las actividades económicas del país es la sequía, el SMN se encarga de detectar el estado actual y la evolución de este fenómeno. Para ello se apoya en el Monitor de Sequía en México (MSM) que a su vez forma parte del Monitor de Sequía de América del Norte (NADM).

### Metodología del MSM

	Se basa en la obtención e interpretación de diversos índices o indicadores de sequía tales como el Índice Estandarizado de Precipitación (SPI) que cuantifica las condiciones de déficit o exceso de precipitación (30, 90, 180, 365 días), Anomalía de Lluvia en Porciento de lo Normal (30, 90, 180, 365 días), Índice Satelital de Salud de la Vegetación (VHI) que mide el grado de estrés de la vegetación a través de la radiancia observada, el Modelo de Humedad del Suelo Leaky Bucket CPC-NOAA que estima la humedad del suelo mediante un modelo hidrológico de una capa, el Índice Normalizado de Diferencia de la Vegetación (NDVI), la Anomalía de la Temperatura Media, el Porcentaje de Disponibilidad de Agua en las presas del país y la aportación de expertos locales. Estos índices se despliegan en capas o layers a través de un Sistema de Información Geográfica (SIG) y mediante un consenso se determinan las regiones afectadas por sequía, de acuerdo a la escala de intensidades que es común en los tres países que va desde anormalmente seco (D0), sequía moderada (D1), sequía severa (D2), sequía extrema (D3) hasta sequía excepcional (D4). Como resultado del consenso se trazan polígonos para cada intensidad de sequía, generando archivos tipo shapefile. Cuando los polígonos corresponden al análisis de mediados de mes (emitido los días 15 de cada mes) se utilizan para cuantificar la sequía sobre el territorio nacional y cuando corresponden a la evaluación final de cualquier mes complementa además al mapa regional o continental del NADM. 

http://smn.cna.gob.mx/es/climatologia/monitor-de-sequia/monitor-de-sequia-en-mexico

## CENAPRED
###############

### Indice Nacional de Inundación
http://datos.gob.mx/busca/dataset/inundaciones
http://datos.gob.mx/busca/dataset/peligro-por-inundaciones-a-nivel-municipal

###Indicadores Municipales de Peligro, Exposición y Vulnerabilidad
http://www.atlasnacionalderiesgos.gob.mx/archivo/indicadores-municipales.html

### Server CENAPRED
	Entrada a su servidor y servicios:
	http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR

	Servicio  [Datos Básicos]
		Censo 2010 - areas geoestadísticas basicas
		Uso de suelo
			Clasificación
			Por tipo de actividad económica
			Áreas Naturales Protegidas
		Hidrología
		Climatología
			Precipitación
			Viento
		Encuesta Intercensal 2015
			Marco Geoestadístico actualizado
			Servicios: 
				Áreas verdes
				Centros de asistencia médica
				tanques de agua
				escuela
				subestación eléctrica
				área verde
				----------
				cementerio
				escuela
				metro
				bombero
				templo

	Servicio [Indicadores]
	http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR/Indicadores/MapServer
		Índice de marginación 2010
		Grado de Vulnerabilidad SOcial 2010
		Índice de Resiliencia CENAPRED 2015
		Perímetros de contención urbana CONAVI 2016

	Químico Tecnológico
		Peligro y Riesgos por incendios Forestales

	Servicio [Sanitario Ecológico]
	http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR/SanitarioEcologicos/MapServer
		Calidad de Agua
		Casos confirmados de zika/chikungunya


	Servicio  [Crisis]
	http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR/Datos_Basicos/MapServer
		zona de peligro por caide de materiales volcánicos
		tsunamis lejanos y ocales
		regiones potenciales de deslizamiento
		hundimientos regionales y agrietamientos
		indice de inundación
		http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR/GoogleCrisis/MapServer/

	Servicio  [Cambio climático]
	http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR/CambioClimatico/MapServer
		Escenarios FUTUROS Cambio climático
			proyecciones de cambio en precipitación promedio
			proyección en cambios de temperatura max y mínima
		Climatología Histórica
			precipitación/temperatura(max, min)
		Municipios más vulnerables al cambio climático

	Servicio  [Fenomenos_Hidrometeorologicos]
	http://servicios1.cenapred.unam.mx:6080/arcgis/rest/services/ANR/Fenomenos_Hidrometeorologicos/MapServer
		Sequía
			históricos y escenarios
		Heladas
		Tormentas de electricidad
		granizo
		nieve
		inundaciones
		ciclones
		tornados


## CONAGUA
###############

	VULNERABILIDAD SOCIAL, ECONÓMICA Y AMBIENTAL


		### Vulnerabilidad ambiental por municipio
			http://datos.gob.mx/busca/dataset/vulnerabilidad-ambiental-por-municipio

		### Grado de Vulnerabilidad Social, económica y ambiental
			http://datos.gob.mx/busca/dataset/vulnerabilidad-social-economica-y-ambiental-por-municipio

		### ÍNDICE DE VULNERABILIDAD GLOBAL [CONAGUA] MUNICIPAL / pdf

			Factores (zj) de la Vulnerabilidad, según el IPCC usados en el estudio de la CONAGUA (2011), a partir de los resultados de la AA2030:
			Grado de exposición
			- 1a: Relación brecha hídrica 2030/Oferta sustentable
			- 1b: Frecuencia de sequías: A, agrícola; H, hidrológica; S, periodo corto (menos de 6 meses); L, periodo largo (más de 6 meses)
			Sensibilidad
			- 2a: Población al 2030
			- 2b: PIB
			- 2c: Impacto económico en la agricultura
			Capacidad de adaptación
			- 3a: Sobre explotación de los acuífero

			http://www.pronacose.gob.mx/pronacose14/contenido/documentos/TablaVulTodoslosMpios_2457_01042016.pdf
	VULNERABILIDAD A SEQUÍA

		### Vulnerabilidad a Sequía (por municipio)
			Se calcula la vulnerabilidad municipal a la sequía a partir del análisis de la vulnerabilidad social, económica y ambiental con 24 indicadores utilizando la metodología del panel intergubernamental de cambio climático (IPCC, 2007)

			http://datos.gob.mx/busca/dataset/vulnerabilidad-a-las-sequias-por-municipio/resource/5ebe9d2c-3be2-4618-a715-fe0e7b827875

		### Municipios por riesgo a las sequías
			A partir del mapa de probabilidad y vulnerabilidad se saca el riesgo y se determinan los municipios con mas alto riesgo a la sequía

			http://datos.gob.mx/busca/dataset/municipios-en-riesgo-por-sequias/resource/6a26869e-44e1-4c26-ab43-5f771f271c49


	### Monitor de Sequía y disponibilidad de Agua

	### Monitor de Sequía [bimestral]
	Se basa en la obtención e interpretación de diversos índices o indicadores de sequía, que mediante un consenso se determinan las regiones afectadas por este fenómeno, de acuerdo a la escala de intensidades que va desde Anormalmente seco (D0), Sequía moderada (D1), Sequía severa (D2), Sequía Extrema (D3) hasta Sequía excepcional (D4).
	Este monitor forma parte del Monitor de Sequía de América del Norte (NADM) y consta de una serie de materiales que incluyen una descripción de la sequía en el país, el conteo de municipios afectados por las diferentes categorías de sequía, tablas y gráficos de porcentaje de área afectada por sequía a nivel nacional, estatal, 13 Regiones Hidrológico-Administrativas y 26 Consejos de cuenca.

	http://smn.cna.gob.mx/es/climatologia/monitor-de-sequia/monitor-de-sequia-en-mexico
	Sequías históricas
	http://datos.gob.mx/busca/dataset/sequias-historicas-en-mexico


	### SEQUÍA HIDROLÓGICA (SDI) [bimestral] MUNICIPAL IMAGEN
	http://www.pronacose.gob.mx/Contenido.aspx?n1=4&n2=21


	### Protocolo Nacional de Alerta Ante Sequía http://www.pronacose.gob.mx/pronacose14/Contenido/Documentos/Protocolo_AlertarSequias.pdf


# Secretaría de Economía
http://www.economia-sniim.gob.mx/nuevo/Consultas/MercadosNacionales/PreciosDeMercado/Agricolas/



Utilización
	Endémicos de pobreza.
		mala utilización 
		Deshidratación
		Diarrea - Desnutrición
		Infección por protozoarios



		Anemia
		marasmo
		kwashiorkor
		
		Parásitos

	líder investigación
	pedir permiso.
	sas
	instituto nacional de salúd pública 

Instituto de ayuda slim 
	- registro de enfermedades crónico degenerativas.
	- 


Variación de Precios de Alimentos

	IPA -Indicator of Price Anomalies
	This indicator is proposed as an indicator for Sustainable development Target 02.c Adopt measures to ensure the proper functioning of food commodity markets and their derivatives and facilitate timely access to market information, including on food reserves, in order to help limit extreme food price volatility.

	Price Trend: Average of the log monthly price changes for the preceding 12 months. Volatility: standard deviation of the og monthly price changes for the preceding 12 months. http://www.fao.org/giews/food-prices/home/en/

	http://www.foodsecurityportal.org/

	Early warning system for vegetable prices
	file:///home/baco/Downloads/sustainability-07-03823.pdf


Costs and benefits of early warning systems
	http://www.preventionweb.net/english/hyogo/gar/2011/en/bgdocs/Rogers_&_Tsirkunov_2011.pdf

	Developing a price warning indicator as an early warning tool - a compound growth approach
	http://www.fao.org/giews/food-prices/research/detail/es/c/235685/

	Developing an indicator of price anomalies as an early warning tool: A compound growth approach
	http://www.fao.org/fileadmin/user_upload/foodprice/docs/resources/Baquedano_2015_Developing%20a%20price%20warning%20indicator%20as%20an%20early%20warning%20tool%20a%20compound%20growth%20approach.pdf

	price warnings
	http://www.fao.org/giews/food-prices/price-warnings/en/
