version: "3"

services:                                                     
  luigi-server:        
    image: dpa/luigi-server 
    ports:
        - "8082:8082"
    env_file: .env
    networks:
      - politica_preventiva_net

  graphdb:
    image: neo4j:3.1
    environment:
      - NEO4J_AUTH=none
    ports:
        - "7474:7474"
        - "7687:7687"
    networks:
      - politica_preventiva_net
    volumes: 
        - politica_preventiva_store:/data

  postgres:
    image: mdillon/postgis:9.5
    volumes:
      - politica_preventiva_store:/var/lib/postgresql
    environment:
      - POSTGRES_USER=maestrosedesol
      - POSTGRES_PASSWORD=foobar # TODO() set password through .env - check secrets 
      - POSTGRES_DB=predictivadb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
        - "5433:5432"
    networks:
      - politica_preventiva_net

volumes:
  politica_preventiva_store:
    external:
      name: politica_preventiva_store

networks:
  politica_preventiva_net:  
    external: true
