version: "3"

services:                                                     
  luigi-server:        
    image: dpa/luigi-server 
    ports:
        - "8082:8082"
    env_file: .env
    networks:
      - politica_preventiva_net

  graphdb:
    image: neo4j:3.1
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - politica_preventiva_net
    volumes: 
        - politica_preventiva_store:/data

volumes:
  politica_preventiva_store:
    external:
      name: politica_preventiva_store

networks:
  politica_preventiva_net:  
    external: true
