version: "3"

services:
  luigi-server-c:
    image: dpa/luigi-server-c
    ports:
        - "8082:8082"
    env_file: .env
    networks:
      - politica_preventiva_net

  graphdb:
    image: neo4j:3.1
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - politica_preventiva_net
    environment:
        - NEO4J_HEAP_MEMORY=2048
        - NEO4J_CACHE_MEMORY=1G
        - NEO4J_AUTH=none

volumes:
  politica_preventiva_store:
    external:
      name: politica_preventiva_store

networks:
  politica_preventiva_net:
    external: true

